### ISSUE TITLE
Unable to Test Repository as It Cannot Be Uploaded

### ISSUE THREAD

**Issue by robo78** [runeharlyk/SpotMicroESP32-Leika#1]
platformio.exe run
Processing esp32cam (board: esp32cam; platform: espressif32; framework: arduino)
------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32cam.html
PLATFORM: Espressif 32 (6.3.2) > AI Thinker ESP32-CAM
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 47 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESP Async WebServer @ 1.2.3+sha.f71e3d4
|-- ArduinoJson @ 6.21.3
|-- Bounce2 @ 2.71.0
|-- NewPing @ 1.9.7
|-- Adafruit SSD1306 @ 2.5.7
|-- Adafruit GFX Library @ 1.11.7
|-- Adafruit BusIO @ 1.14.1
|-- Adafruit PWM Servo Driver Library @ 2.4.1
|-- Adafruit ADS1X15 @ 2.4.0
|-- Adafruit HMC5883 Unified @ 1.2.1
|-- Adafruit Unified Sensor @ 1.1.11
|-- UrlEncode @ 1.0.1
|-- MPU6050_light @ 1.1.0
|-- HTTPClient @ 2.0.0
|-- SPIFFS @ 2.0.0
|-- ArduinoOTA @ 2.0.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- WiFi @ 2.0.0
|-- Wire @ 2.0.0
|-- Update @ 2.0.0
Building in release mode
Compiling .pio\build\esp32cam\src\camera.cpp.o
Compiling .pio\build\esp32cam\src\deviceconfig.cpp.o
Compiling .pio\build\esp32cam\src\jsonserializer.cpp.o
Compiling .pio\build\esp32cam\src\main.cpp.o
Compiling .pio\build\esp32cam\src\network.cpp.o
Compiling .pio\build\esp32cam\src\servo.cpp.o
Compiling .pio\build\esp32cam\src\webserver.cpp.o
Compiling .pio\build\esp32cam\lib8da\FS\vfs_api.cpp.o
In file included from src/camera.cpp:2:
include/camera_pins.h:296:2: error: #error "Camera model not selected"
 #error "Camera model not selected"
  ^~~~~
In file included from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
src/camera.cpp: In function 'esp_err_t InitializeCamera()':
src/camera.cpp:9:28: error: 'Y2_GPIO_NUM' was not declared in this scope
     camera_config.pin_d0 = Y2_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:9:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d0 = Y2_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:10:28: error: 'Y3_GPIO_NUM' was not declared in this scope
     camera_config.pin_d1 = Y3_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:10:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d1 = Y3_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:11:28: error: 'Y4_GPIO_NUM' was not declared in this scope
     camera_config.pin_d2 = Y4_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:11:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d2 = Y4_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:12:28: error: 'Y5_GPIO_NUM' was not declared in this scope
     camera_config.pin_d3 = Y5_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:12:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d3 = Y5_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:13:28: error: 'Y6_GPIO_NUM' was not declared in this scope
     camera_config.pin_d4 = Y6_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:13:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d4 = Y6_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:14:28: error: 'Y7_GPIO_NUM' was not declared in this scope
     camera_config.pin_d5 = Y7_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:14:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d5 = Y7_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:15:28: error: 'Y8_GPIO_NUM' was not declared in this scope
     camera_config.pin_d6 = Y8_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:15:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d6 = Y8_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:16:28: error: 'Y9_GPIO_NUM' was not declared in this scope
     camera_config.pin_d7 = Y9_GPIO_NUM;
                            ^~~~~~~~~~~
src/camera.cpp:16:28: note: suggested alternative: 'GPIO_NUM_9'
     camera_config.pin_d7 = Y9_GPIO_NUM;
                            ^~~~~~~~~~~
                            GPIO_NUM_9
src/camera.cpp:17:30: error: 'XCLK_GPIO_NUM' was not declared in this scope
     camera_config.pin_xclk = XCLK_GPIO_NUM;
                              ^~~~~~~~~~~~~
src/camera.cpp:17:30: note: suggested alternative: 'SPI_CLK_GPIO_NUM'
     camera_config.pin_xclk = XCLK_GPIO_NUM;
                              ^~~~~~~~~~~~~
                              SPI_CLK_GPIO_NUM
src/camera.cpp:18:30: error: 'PCLK_GPIO_NUM' was not declared in this scope
     camera_config.pin_pclk = PCLK_GPIO_NUM;
                              ^~~~~~~~~~~~~
src/camera.cpp:18:30: note: suggested alternative: 'SPI_CLK_GPIO_NUM'
     camera_config.pin_pclk = PCLK_GPIO_NUM;
                              ^~~~~~~~~~~~~
                              SPI_CLK_GPIO_NUM
src/camera.cpp:19:31: error: 'VSYNC_GPIO_NUM' was not declared in this scope
     camera_config.pin_vsync = VSYNC_GPIO_NUM;
                               ^~~~~~~~~~~~~~
In file included from include/servo.h:6,
                 from include/globals.h:72,
                 from src/main.cpp:1:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
In file included from include/servo.h:6,
                 from include/globals.h:72,
                 from src/deviceconfig.cpp:3:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
src/camera.cpp:19:31: note: suggested alternative: 'SPI_D_GPIO_NUM'
     camera_config.pin_vsync = VSYNC_GPIO_NUM;
                               ^~~~~~~~~~~~~~
                               SPI_D_GPIO_NUM
src/camera.cpp:20:30: error: 'HREF_GPIO_NUM' was not declared in this scope
     camera_config.pin_href = HREF_GPIO_NUM;
                              ^~~~~~~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
src/camera.cpp:20:30: note: suggested alternative: 'SPI_D_GPIO_NUM'
     camera_config.pin_href = HREF_GPIO_NUM;
                              ^~~~~~~~~~~~~
                              SPI_D_GPIO_NUM
src/camera.cpp:21:19: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
     camera_config.pin_sscb_sda = SIOD_GPIO_NUM;
                   ^~~~~~~~~~~~
In file included from include/AsyncJpegStream.h:2,
                 from include/webserver.h:12,
                 from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
C:/Users/rzieb/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h:117:87: note: declared here
         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
                                                                                       ^
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
src/camera.cpp:21:19: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
     camera_config.pin_sscb_sda = SIOD_GPIO_NUM;
                   ^~~~~~~~~~~~
In file included from include/AsyncJpegStream.h:2,
                 from include/webserver.h:12,
                 from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
C:/Users/rzieb/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h:117:87: note: declared here
         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
                                                                                       ^
src/camera.cpp:21:19: warning: 'camera_config_t::<unnamed union>::pin_sscb_sda' is deprecated: please use pin_sccb_sda instead [-Wdeprecated-declarations]
     camera_config.pin_sscb_sda = SIOD_GPIO_NUM;
                   ^~~~~~~~~~~~
In file included from include/AsyncJpegStream.h:2,
                 from include/webserver.h:12,
                 from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
C:/Users/rzieb/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h:117:87: note: declared here
         int pin_sscb_sda __attribute__((deprecated("please use pin_sccb_sda instead")));           /*!< GPIO pin for camera SDA line (legacy name) */
                                                                                       ^
src/camera.cpp:21:34: error: 'SIOD_GPIO_NUM' was not declared in this scope
     camera_config.pin_sscb_sda = SIOD_GPIO_NUM;
                                  ^~~~~~~~~~~~~
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
src/camera.cpp:21:34: note: suggested alternative: 'SPI_D_GPIO_NUM'
     camera_config.pin_sscb_sda = SIOD_GPIO_NUM;
                                  ^~~~~~~~~~~~~
                                  SPI_D_GPIO_NUM
src/camera.cpp:22:19: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
     camera_config.pin_sscb_scl = SIOC_GPIO_NUM;
                   ^~~~~~~~~~~~
In file included from include/AsyncJpegStream.h:2,
                 from include/webserver.h:12,
                 from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
C:/Users/rzieb/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h:121:87: note: declared here
         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
                                                                                       ^
src/camera.cpp:22:19: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
     camera_config.pin_sscb_scl = SIOC_GPIO_NUM;
                   ^~~~~~~~~~~~
In file included from include/servo.h:6,
                 from include/globals.h:72,
                 from src/network.cpp:1:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
In file included from include/AsyncJpegStream.h:2,
                 from include/webserver.h:12,
                 from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
C:/Users/rzieb/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h:121:87: note: declared here
         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
                                                                                       ^
src/camera.cpp:22:19: warning: 'camera_config_t::<unnamed union>::pin_sscb_scl' is deprecated: please use pin_sccb_scl instead [-Wdeprecated-declarations]
     camera_config.pin_sscb_scl = SIOC_GPIO_NUM;
                   ^~~~~~~~~~~~
In file included from include/AsyncJpegStream.h:2,
                 from include/webserver.h:12,
                 from include/globals.h:80,
                 from include/servo.h:5,
                 from src/camera.cpp:1:
C:/Users/rzieb/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include/esp_camera.h:121:87: note: declared here
         int pin_sscb_scl __attribute__((deprecated("please use pin_sccb_scl instead")));           /*!< GPIO pin for camera SCL line (legacy name) */
                                                                                       ^
src/camera.cpp:22:34: error: 'SIOC_GPIO_NUM' was not declared in this scope
     camera_config.pin_sscb_scl = SIOC_GPIO_NUM;
                                  ^~~~~~~~~~~~~
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
In file included from include/servo.h:6,
                 from include/globals.h:72,
                 from src/jsonserializer.cpp:1:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
src/camera.cpp:22:34: note: suggested alternative: 'SPI_D_GPIO_NUM'
     camera_config.pin_sscb_scl = SIOC_GPIO_NUM;
                                  ^~~~~~~~~~~~~
                                  SPI_D_GPIO_NUM
src/camera.cpp:23:30: error: 'PWDN_GPIO_NUM' was not declared in this scope
     camera_config.pin_pwdn = PWDN_GPIO_NUM;
                              ^~~~~~~~~~~~~
src/camera.cpp:23:30: note: suggested alternative: 'SPI_D_GPIO_NUM'
     camera_config.pin_pwdn = PWDN_GPIO_NUM;
                              ^~~~~~~~~~~~~
                              SPI_D_GPIO_NUM
src/camera.cpp:24:31: error: 'RESET_GPIO_NUM' was not declared in this scope
     camera_config.pin_reset = RESET_GPIO_NUM;
                               ^~~~~~~~~~~~~~
In file included from include/globals.h:80,
                 from include/servo.h:5,
                 from src/servo.cpp:1:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
src/camera.cpp:24:31: note: suggested alternative: 'SPI_D_GPIO_NUM'
     camera_config.pin_reset = RESET_GPIO_NUM;
                               ^~~~~~~~~~~~~~
                               SPI_D_GPIO_NUM
src/network.cpp: In function 'bool ConnectToWiFi(uint)':
src/network.cpp:18:22: error: 'HOSTNAME' was not declared in this scope
     WiFi.setHostname(HOSTNAME);
                      ^~~~~~~~
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
src/network.cpp:18:22: note: suggested alternative: 'ESTALE'
     WiFi.setHostname(HOSTNAME);
                      ^~~~~~~~
                      ESTALE
src/network.cpp:61:40: error: 'HTTP_PORT' was not declared in this scope
         MDNS.addService("http", "tcp", HTTP_PORT);
                                        ^~~~~~~~~
src/network.cpp:61:40: note: suggested alternative: 'HTTP_POST'
         MDNS.addService("http", "tcp", HTTP_PORT);
                                        ^~~~~~~~~
                                        HTTP_POST
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
In file included from include/servo.h:6,
                 from include/globals.h:72,
                 from src/webserver.cpp:1:
include/webserver.h: In constructor 'CWebServer::CWebServer()':
include/webserver.h:123:19: error: 'HTTP_PORT' was not declared in this scope
         : _server(HTTP_PORT)
                   ^~~~~~~~~
include/webserver.h:123:19: note: suggested alternative: 'HTTP_POST'
         : _server(HTTP_PORT)
                   ^~~~~~~~~
                   HTTP_POST
include/webserver.h:125:15: error: 'WEBSOCKET_PATH' was not declared in this scope
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
include/webserver.h:125:15: note: suggested alternative: 'LWIP_SOCKET_POLL'
         , _ws(WEBSOCKET_PATH)
               ^~~~~~~~~~~~~~
               LWIP_SOCKET_POLL
include/webserver.h: In member function 'void CWebServer::begin()':
include/webserver.h:133:56: error: 'HOSTNAME' was not declared in this scope
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
include/webserver.h:133:56: note: suggested alternative: 'ESTALE'
         DefaultHeaders::Instance().addHeader("Server", HOSTNAME);
                                                        ^~~~~~~~
                                                        ESTALE
*** [.pio\build\esp32cam\src\camera.cpp.o] Error 1
*** [.pio\build\esp32cam\src\deviceconfig.cpp.o] Error 1
*** [.pio\build\esp32cam\src\network.cpp.o] Error 1
*** [.pio\build\esp32cam\src\main.cpp.o] Error 1
*** [.pio\build\esp32cam\src\servo.cpp.o] Error 1
*** [.pio\build\esp32cam\src\jsonserializer.cpp.o] Error 1
*** [.pio\build\esp32cam\src\webserver.cpp.o] Error 1
============================================== [FAILED] Took 7.41 seconds ==============================================

**Comment by runeharlyk** [comment]
Hi! Thank you for showing interest in my project.
It seems I forgot to add the example configuration and section in the readme about what to do with it.
I have added both now. To build the project for the first time you have to:
1. Make a copy of *`include/secrets.example.h`* in the same folder
1. Rename the copy to *`secrets.h`*
1. Configure relevant settings

Let me know if you get it to work

**Comment by robo78** [comment]
Duplicate data is in config.h and secrets.h. The tile is not visible on the network despite these settings.

**Comment by runeharlyk** [comment]
I have remove the duplicated defines 😁 
What system are you using? And Is it the device that cant connect to the network or do you mean you cannot see it using the mDNS address?

**Comment by robo78** [comment]
npm run dev uruchmia page on localhost but esp32cam does not fire anything and I do not see the connection.I see the IP of the device but I do not know how to connect and on what port, serial monitor does not display any information

**Comment by robo78** [comment]
The board was broken, now it works, testing
