### ISSUE TITLE
ESP32 Cam not working 

### ISSUE THREAD

**Issue by Ian-cmd-ops** [runeharlyk/SpotMicroESP32-Leika#37]
I can't get the my ESP32 cam to stream or view after I got my ESP32 Uploaded with via PIO.

**Comment by Ian-cmd-ops** [comment]
![image](https://github.com/runeharlyk/SpotMicroESP32-Leika/assets/78785932/bfc78c40-2bf4-424a-b745-3f02d530b6b7)
![Screenshot 2024-04-25 232749](https://github.com/runeharlyk/SpotMicroESP32-Leika/assets/78785932/e753a237-64ab-46c2-bc51-737ca301d99a)
do I need the other modules attached first before it runs

**Comment by Ian-cmd-ops** [comment]
#define USE_PSRAM true

#define USE_WIFI true

#define WAIT_FOR_WIFI false

#define USE_WEBSERVER true

#define USE_WEBSERVER_SSL false

#define USE_WEBSOCKET true

#define USE_OAT false

#define USE_NTP false

#define USE_MDNS true

#define USE_DNS_SERVER false

#define USE_REMOTE_SERIAL false

#define USE_LOW_POWER false

#define USE_CAMERA true

#define USE_MPU true

#define USE_POWER_BUTTON true

#define USE_USS true

**Comment by runeharlyk** [comment]
The camera stream should work out of the box. Is there anything in the browser console log?

**Comment by Ian-cmd-ops** [comment]
Bad ESP32 Cam
