### ISSUE TITLE
Pin Out documentation

### ISSUE THREAD

**Issue by Ian-cmd-ops** [runeharlyk/SpotMicroESP32-Leika#45]
I'm looking for better documentation for pin out and better electronics schematics/layout for assembly. Might need an additional part for I2C bus expansion.

**Comment by Ian-cmd-ops** [comment]
Also /peripherals/cams doesn't work and I can't connect to my local network. Only the AP works 
![image](https://github.com/runeharlyk/SpotMicroESP32-Leika/assets/78785932/6795d29f-9b8d-4964-bdfb-9856ddd66eef)

**Comment by runeharlyk** [comment]
I have added some [documentation](https://github.com/runeharlyk/SpotMicroESP32-Leika/tree/master/docs) as well as a [circuit digram](https://github.com/runeharlyk/SpotMicroESP32-Leika/blob/master/docs/2_assembly.md) on how to get started. Its still a bit rough, but should contain some useful information.

As for you problems, what does the serial monitor say? Does the esp32 try to connect? Have you added your wifi from `/wifi/sta`?

**Comment by Ian-cmd-ops** [comment]
I got the wifi to work. My latest issue is that I get this.
Also Peripherals on the main page have a drop down. 
I noticed that you don't have a calibration down or have a settings to PCA9685 for calibration the servos 
![image](https://github.com/runeharlyk/SpotMicroESP32-Leika/assets/78785932/6d76d454-59d5-43a9-9092-3e40a91866ce)

**Comment by Ian-cmd-ops** [comment]
> I have added some [documentation](https://github.com/runeharlyk/SpotMicroESP32-Leika/tree/master/docs) as well as a [circuit digram](https://github.com/runeharlyk/SpotMicroESP32-Leika/blob/master/docs/2_assembly.md) on how to get started. Its still a bit rough, but should contain some useful information.
> 
> As for you problems, what does the serial monitor say? Does the esp32 try to connect? Have you added your wifi from `/wifi/sta`?

i added it and got it the SSID to connect.

**Comment by Ian-cmd-ops** [comment]
![image](https://github.com/runeharlyk/SpotMicroESP32-Leika/assets/78785932/49ecf051-7da6-465e-85b0-34588dfaf668)
Still having issues with the camera on this latest build. Using a ESP32 Cam.

**Comment by Ian-cmd-ops** [comment]
Marking issue as closed. Didn’t use the correct build environment.
